image: php:latest

services:
  - mysql:latest

variables:
  MYSQL_DATABASE: testMoostack
  MYSQL_USERNAME: root
  MYSQL_ROOT_PASSWORD: root

cache:
  paths:
  - vendor/
  - node_modules/

before_script:
  - apt-get update -yqq
  - curl -sL https://deb.nodesource.com/setup_7.x | bash -
  - apt-get install git nodejs libcurl4-gnutls-dev libicu-dev libmcrypt-dev libvpx-dev libjpeg-dev libpng-dev libxpm-dev zlib1g-dev libfreetype6-dev libxml2-dev libexpat1-dev libbz2-dev libgmp3-dev libldap2-dev unixodbc-dev libpq-dev libsqlite3-dev libaspell-dev libsnmp-dev libpcre3-dev libtidy-dev -yqq
  - docker-php-ext-install mbstring pdo_mysql curl json intl gd xml zip bz2 opcache
  - pecl install xdebug
  - docker-php-ext-enable xdebug
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar install
  - npm install
  - cp .env.example .env
  - npm run dev
  - php artisan key:generate
  - php artisan config:cache
  - php artisan migrate
  - php artisan db:seed
test:
  script:
  - php vendor/bin/phpunit --coverage-text --colors=true

